name: Continuos integration

on:
  push:
    branches: [ main, master, feature-lab-final ]
  pull_request:
    branches: [ main, master, feature-lab-final ]

jobs: 
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.jobs
        uses: actions/setup-node@v2
        with:
          node-version: 24.
      - name: run install, build and test
        run: |
          npm install
          npm run build
          npm run test
          npm run bash

#adicionando um texto para realizar um pull request
#git actions